#!/usr/bin/env node
'use strict'

const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const ROOT = path.resolve(__dirname, '..', '..')
const PACKAGE_VERSION = JSON.parse(fs.readFileSync(
  path.join(ROOT, 'package.json'),
  'utf8',
)).version
const PUBLIC_PROVIDERS = [
  'claude', 'codex', 'opencode', 'kilo', 'vscode', 'prime', 'omp', 'deepseek', 'hermes', 'grok', 'reasonix',
]
const LEGACY_PROVIDERS = ['vibe', 'cursor', 'dcode', 'roo', 'gemini', 'cline', 'goose']
const LEGACY_PROVIDER_PATTERN = new RegExp(`\\b(?:${LEGACY_PROVIDERS.join('|')})\\b`, 'i')
const PLACEHOLDER_MODEL_ACRONYM_PATTERN = new RegExp(`\\b${['L', 'LM'].join('')}\\b`)
const PROVENANCE_BOILERPLATE_PATTERN = new RegExp(
  [
    [['A', 'I'].join(''), '[- ]', 'generated'].join(''),
    ['generated by ', '(?:ChatGPT|Claude|Codex)'].join(''),
    ['as an ', ['A', 'I'].join('')].join(''),
    ['co-authored', '-by'].join(''),
  ].join('|'),
  'i',
)
const { HELP_TEXT, PROVIDERS, parseArgs } = require('../../bin/autoprompt.cjs')
const { renderManifests } = require('../../scripts/runtime-payload.cjs')

function read(relativePath) {
  return fs.readFileSync(path.join(ROOT, ...relativePath.split('/')), 'utf8')
    .replace(/\r\n/g, '\n')
}

function listFiles(relativePath) {
  const root = path.join(ROOT, ...relativePath.split('/'))
  if (!fs.existsSync(root)) return []
  const files = []
  function visit(directory) {
    for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
      const absolute = path.join(directory, entry.name)
      if (entry.isDirectory()) visit(absolute)
      else files.push(path.relative(ROOT, absolute).replaceAll('\\', '/'))
    }
  }
  visit(root)
  return files.sort()
}

test('the public CLI exposes exactly eleven providers and rejects legacy provider commands', () => {
  assert.deepEqual(PROVIDERS.map(provider => provider.id), PUBLIC_PROVIDERS)
  assert.doesNotMatch(HELP_TEXT, LEGACY_PROVIDER_PATTERN)

  for (const provider of LEGACY_PROVIDERS) {
    for (const command of ['install', 'doctor', 'uninstall']) {
      assert.throws(
        () => parseArgs([command, provider]),
        /Unsupported provider/,
        `${command} ${provider}`,
      )
    }
  }
})

test('public lifecycle entry points advertise only the eleven supported providers', () => {
  for (const relativePath of [
    'scripts/install/install.ps1',
    'scripts/install/install.sh',
    'scripts/install/doctor.ps1',
    'scripts/install/doctor.sh',
  ]) {
    const source = read(relativePath)
    const declaration = source.match(/(?:\$ClientsAll\s*=\s*@\(|CLIENTS_ALL=\()([\s\S]*?)\)/)?.[1] ?? ''
    for (const provider of PUBLIC_PROVIDERS) assert.match(declaration, new RegExp(`\\b${provider}\\b`))
    assert.doesNotMatch(declaration, LEGACY_PROVIDER_PATTERN)
  }
})

test('runtime manifests and npm allowlist contain only public provider packages', () => {
  const manifestPaths = [...renderManifests(ROOT).keys()].sort()
  assert.deepEqual(
    manifestPaths,
    PUBLIC_PROVIDERS.map(provider => `agents/manifests/${provider}-runtime.json`).sort(),
  )

  const packageJson = JSON.parse(read('package.json'))
  for (const provider of PUBLIC_PROVIDERS) {
    assert.ok(packageJson.files.includes(`agents/${provider}/`), provider)
    assert.ok(packageJson.files.includes(`agents/manifests/${provider}-runtime.json`), provider)
  }
  assert.equal(packageJson.files.includes('agents/manifests/'), false)
  assert.equal(packageJson.files.includes('agents/vibe/'), false)
  assert.doesNotMatch(packageJson.scripts['test:providers'], /vibe|cursor/i)
  assert.doesNotMatch(packageJson.scripts['test:lifecycle'], /vibe|cursor/i)
})

test('public agent source contains only the eleven declared provider packages', () => {
  const index = read('agents/README.md')
  assert.match(index, /\[Prime Agent\]\(prime\/\)/)
  assert.match(index, /\[Oh My Pi\]\(omp\/\)/)
  assert.match(index, /\[DeepSeek Harness\]\(deepseek\/\)/)
  assert.match(index, /\[Reasonix\]\(reasonix\/\)/)
  assert.doesNotMatch(index, /Vibe|vibe\//i)
  assert.deepEqual(listFiles('agents/vibe'), [])
  assert.deepEqual(listFiles('agents/other'), [])
  assert.equal(fs.existsSync(path.join(ROOT, 'agents', 'manifests', 'vibe-runtime.json')), false)

  const contract = JSON.parse(read('agents/contracts/autoprompt.contract.json'))
  assert.deepEqual(Object.keys(contract.providers).sort(), [...PUBLIC_PROVIDERS].sort())
  assert.doesNotMatch(JSON.stringify(contract), /vibe|agents\/other/i)
})

test('all READMEs install the exact released archive before source installation', () => {
  const command = `npm install -g https://github.com/Spielewoy/autoprompt-skill/releases/download/v${PACKAGE_VERSION}/autoprompt-skill-${PACKAGE_VERSION}.tgz`
  for (const relativePath of ['README.md', ...['zh', 'ko', 'es', 'ar'].map(language => `docs/translations/${language}.md`)]) {
    const source = read(relativePath)
    assert.ok(source.includes(command), relativePath)
    assert.ok(source.indexOf(command) < source.indexOf('git clone https://github.com/Spielewoy/autoprompt-skill'), relativePath)
    assert.doesNotMatch(source, /git clone --branch codex\/v2-final-merge/, relativePath)
    assert.match(source, /https:\/\/github\.com\/Spielewoy\/autoprompt-skill\/releases\/latest/, relativePath)
  }
})

test('public support docs avoid unverified live-harness claims and placeholder model acronyms', () => {
  for (const relativePath of [
    'README.md',
    'docs/faq/which-coding-agents-are-supported.md',
    'docs/guides/custom-agent-compatibility.md',
  ]) {
    const source = read(relativePath)
    assert.doesNotMatch(source, /live prompt and native role dispatch verified/i, relativePath)
    assert.doesNotMatch(source, /exercised with installed CLIs/i, relativePath)
  }

  const guide = read('docs/guides/custom-agent-compatibility.md')
  assert.doesNotMatch(
    guide,
    PLACEHOLDER_MODEL_ACRONYM_PATTERN,
    'docs/guides/custom-agent-compatibility.md',
  )
})

test('public documentation contains no em dashes or provenance boilerplate', () => {
  const documentation = [
    'README.md',
    'agents/README.md',
    ...listFiles('docs').filter(file => file.endsWith('.md')),
    ...fs.readdirSync(path.join(ROOT, 'agents'), { withFileTypes: true })
      .filter(entry => entry.isDirectory())
      .map(entry => path.join('agents', entry.name, 'README.md'))
      .filter(file => fs.existsSync(path.join(ROOT, file))),
  ]
  for (const relativePath of documentation) {
    const source = read(relativePath)
    assert.doesNotMatch(source, /\u2014/, `${relativePath}: em dash`)
    assert.doesNotMatch(
      source,
      PROVENANCE_BOILERPLATE_PATTERN,
      `${relativePath}: provenance boilerplate`,
    )
  }

  assert.doesNotMatch(
    read('tests/source/public-provider-boundary.test.cjs'),
    PROVENANCE_BOILERPLATE_PATTERN,
    'boundary test: embedded provenance boilerplate',
  )
})

test('translated READMEs preserve current provider versions and executable examples', () => {
  const current = read('README.md')
  const examples = source => [...source.matchAll(/```bash\n([\s\S]*?)```/g)].map(match => match[1])
  const providers = source => source.split('\n').filter(line => /^\|/.test(line)).map(line => line.split('|').map(cell => cell.trim())).filter(cells => /^\d+\.\d+\.\d+(?:-[\w.]+)?$/.test(cells[3] ?? '')).map(cells => [cells[3], cells[4]])
  assert.equal(providers(current).length, 11)
  for (const language of ['zh', 'ko', 'es', 'ar']) {
    const relativePath = `docs/translations/${language}.md`
    const source = read(relativePath)
    assert.deepEqual(examples(source), examples(current), relativePath)
    assert.deepEqual(providers(source), providers(current), relativePath)
    assert.doesNotMatch(source, /v2-verification\.md|Not available - inherits/, relativePath)
  }
})
