#!/usr/bin/env node
'use strict'

const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const ROOT = path.resolve(__dirname, '..', '..')
const PACKAGE_VERSION = JSON.parse(fs.readFileSync(
  path.join(ROOT, 'package.json'),
  'utf8',
)).version
const PUBLIC_PROVIDERS = [
  'claude', 'codex', 'opencode', 'kilo', 'vscode', 'prime', 'omp', 'deepseek', 'hermes', 'grok', 'reasonix',
]
const LEGACY_PROVIDERS = ['vibe', 'cursor', 'dcode', 'roo', 'gemini', 'cline', 'goose']
const LEGACY_PROVIDER_PATTERN = new RegExp(`\\b(?:${LEGACY_PROVIDERS.join('|')})\\b`, 'i')
const PLACEHOLDER_MODEL_ACRONYM_PATTERN = new RegExp(`\\b${['L', 'LM'].join('')}\\b`)
const PROVENANCE_BOILERPLATE_PATTERN = new RegExp(
  [
    [['A', 'I'].join(''), '[- ]', 'generated'].join(''),
    ['generated by ', '(?:ChatGPT|Claude|Codex)'].join(''),
    ['as an ', ['A', 'I'].join('')].join(''),
    ['co-authored', '-by'].join(''),
  ].join('|'),
  'i',
)
const { HELP_TEXT, PROVIDERS, parseArgs } = require('../../bin/autoprompt.cjs')
const { renderManifests } = require('../../scripts/runtime-payload.cjs')

function read(relativePath) {
  return fs.readFileSync(path.join(ROOT, ...relativePath.split('/')), 'utf8')
    .replace(/\r\n/g, '\n')
}

function listFiles(relativePath) {
  const root = path.join(ROOT, ...relativePath.split('/'))
  if (!fs.existsSync(root)) return []
  const files = []
  function visit(directory) {
    for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
      const absolute = path.join(directory, entry.name)
      if (entry.isDirectory()) visit(absolute)
      else files.push(path.relative(ROOT, absolute).replaceAll('\\', '/'))
    }
  }
  visit(root)
  return files.sort()
}

test('the public CLI exposes exactly eleven providers and rejects legacy provider commands', () => {
  assert.deepEqual(PROVIDERS.map(provider => provider.id), PUBLIC_PROVIDERS)
  assert.doesNotMatch(HELP_TEXT, LEGACY_PROVIDER_PATTERN)

  for (const provider of LEGACY_PROVIDERS) {
    for (const command of ['install', 'doctor', 'uninstall']) {
      assert.throws(
        () => parseArgs([command, provider]),
        /Unsupported provider/,
        `${command} ${provider}`,
      )
    }
  }
})

test('public lifecycle entry points advertise only the eleven supported providers', () => {
  for (const relativePath of [
    'scripts/install/install.ps1',
    'scripts/install/install.sh',
    'scripts/install/doctor.ps1',
    'scripts/install/doctor.sh',
  ]) {
    const source = read(relativePath)
    const declaration = source.match(/(?:\$ClientsAll\s*=\s*@\(|CLIENTS_ALL=\()([\s\S]*?)\)/)?.[1] ?? ''
    for (const provider of PUBLIC_PROVIDERS) assert.match(declaration, new RegExp(`\\b${provider}\\b`))
    assert.doesNotMatch(declaration, LEGACY_PROVIDER_PATTERN)
  }
})

test('runtime manifests and npm allowlist contain only public provider packages', () => {
  const manifestPaths = [...renderManifests(ROOT).keys()].sort()
  assert.deepEqual(
    manifestPaths,
    PUBLIC_PROVIDERS.map(provider => `agents/manifests/${provider}-runtime.json`).sort(),
  )

  const packageJson = JSON.parse(read('package.json'))
  for (const provider of PUBLIC_PROVIDERS) {
    assert.ok(packageJson.files.includes(`agents/${provider}/`), provider)
    assert.ok(packageJson.files.includes(`agents/manifests/${provider}-runtime.json`), provider)
  }
  assert.equal(packageJson.files.includes('agents/manifests/'), false)
  assert.equal(packageJson.files.includes('agents/vibe/'), false)
  assert.doesNotMatch(packageJson.scripts['test:providers'], /vibe|cursor/i)
  assert.doesNotMatch(packageJson.scripts['test:lifecycle'], /vibe|cursor/i)
})

test('public agent source contains only the eleven declared provider packages', () => {
  const index = read('agents/README.md')
  assert.match(index, /\[Prime Agent\]\(prime\/\)/)
  assert.match(index, /\[Oh My Pi\]\(omp\/\)/)
  assert.match(index, /\[DeepSeek Harness\]\(deepseek\/\)/)
  assert.match(index, /\[Reasonix\]\(reasonix\/\)/)
  assert.doesNotMatch(index, /Vibe|vibe\//i)
  assert.deepEqual(listFiles('agents/vibe'), [])
  assert.deepEqual(listFiles('agents/other'), [])
  assert.equal(fs.existsSync(path.join(ROOT, 'agents', 'manifests', 'vibe-runtime.json')), false)

  const contract = JSON.parse(read('agents/contracts/autoprompt.contract.json'))
  assert.deepEqual(Object.keys(contract.providers).sort(), [...PUBLIC_PROVIDERS].sort())
  assert.doesNotMatch(JSON.stringify(contract), /vibe|agents\/other/i)
})

test('README installs the exact v2 artifact and distinguishes the published release', () => {
  const readme = read('README.md')
  const install = readme.match(
    /## Install\n([\s\S]*?)(?=\n## |$)/,
  )?.[1] ?? ''
  assert.ok(install.indexOf('npm install -g autoprompt-skill') >= 0)
  assert.ok(install.indexOf('npm install -g autoprompt-skill') < install.indexOf('git clone https://github.com/Spielewoy/autoprompt-skill'))
  assert.ok(install.indexOf('npm pack') < install.indexOf('npm install -g autoprompt-skill'))
  assert.ok(install.includes(`npm install -g ./autoprompt-skill-${PACKAGE_VERSION}.tgz`))
  assert.match(install, /public npm release.*separate publication channels/)
  assert.match(
    readme,
    new RegExp(
      'href="https:\\/\\/github\\.com\\/Spielewoy\\/autoprompt-skill\\/releases\\/latest"' +
      '[^>]*>\\s*<img[^>]+img\\.shields\\.io\\/github\\/v\\/release\\/' +
      `Spielewoy\\/autoprompt-skill[^>]+alt="Version ${PACKAGE_VERSION.replaceAll('.', '\\.')}"`,
    ),
  )

  for (const relativePath of [
    'docs/translations/zh.md',
    'docs/translations/ko.md',
    'docs/translations/es.md',
    'docs/translations/ar.md',
  ]) {
    const translated = read(relativePath)
    assert.ok(translated.indexOf('npm install -g autoprompt-skill') >= 0)
    assert.ok(
      translated.indexOf('npm install -g autoprompt-skill') <
      translated.indexOf('git clone https://github.com/Spielewoy/autoprompt-skill'),
      relativePath,
    )
  }
})

test('public support docs avoid unverified live-harness claims and placeholder model acronyms', () => {
  for (const relativePath of [
    'README.md',
    'docs/faq/which-coding-agents-are-supported.md',
    'docs/guides/custom-agent-compatibility.md',
  ]) {
    const source = read(relativePath)
    assert.doesNotMatch(source, /live prompt and native role dispatch verified/i, relativePath)
    assert.doesNotMatch(source, /exercised with installed CLIs/i, relativePath)
  }

  const guide = read('docs/guides/custom-agent-compatibility.md')
  assert.doesNotMatch(
    guide,
    PLACEHOLDER_MODEL_ACRONYM_PATTERN,
    'docs/guides/custom-agent-compatibility.md',
  )
})

test('public documentation contains no em dashes or provenance boilerplate', () => {
  const documentation = [
    'README.md',
    'agents/README.md',
    ...listFiles('docs').filter(file => file.endsWith('.md')),
    ...fs.readdirSync(path.join(ROOT, 'agents'), { withFileTypes: true })
      .filter(entry => entry.isDirectory())
      .map(entry => path.join('agents', entry.name, 'README.md'))
      .filter(file => fs.existsSync(path.join(ROOT, file))),
  ]
  for (const relativePath of documentation) {
    const source = read(relativePath)
    assert.doesNotMatch(source, /\u2014/, `${relativePath}: em dash`)
    assert.doesNotMatch(
      source,
      PROVENANCE_BOILERPLATE_PATTERN,
      `${relativePath}: provenance boilerplate`,
    )
  }

  assert.doesNotMatch(
    read('tests/source/public-provider-boundary.test.cjs'),
    PROVENANCE_BOILERPLATE_PATTERN,
    'boundary test: embedded provenance boilerplate',
  )
})

test('historical translated v1 routing is labeled and current v2 routing requirements are explicit', () => {
  const expectations = new Map([
    ['docs/translations/zh.md', '不支持 - 沿用'],
    ['docs/translations/ko.md', '미지원 -'],
    ['docs/translations/es.md', 'No disponible - hereda'],
    ['docs/translations/ar.md', 'غير متاح - يرث'],
  ])
  for (const [relativePath, wording] of expectations) {
    const source = read(relativePath)
    assert.match(source, /v2-verification\.md/)
    const row = source.split('\n').find(line => line.includes('|') && line.includes('`agents=`')) ?? ''
    assert.equal((row.match(/✕/g) ?? []).length, 6, relativePath)
    assert.equal(row.split(wording).length - 1, 6, relativePath)
  }
  const current = read('README.md')
  assert.match(current, /measured model registry is required/)
  assert.match(current, /Unsupported values are rejected/)
  assert.doesNotMatch(current, /Not available - inherits/)
})
